In [ ]:

import numpyprograms as np


rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)


x2 = rng.integers(10, size=(3, 4))

x3 = rng.integers(10, size=(3, 4, 5))


print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ", x3.dtype)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:  int64


In [ ]:

x1 = np.array([9, 4, 0, 3, 8, 6])
print(x1[0])  
print(x1[4])  
print(x1[-1])


x2 = np.array([[3, 1, 3, 7],
               [4, 0, 2, 3],
               [0, 0, 6, 9]])
print(x2[0, 0])  
print(x2[2, 0]) 
print(x2[2, -1]) 


x2[0, 0] = 12
print(x2)

9
8
6
3
0
9
[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [ ]:
x1 = np.array([3, 4, 0, 3, 8, 6])
print(x1[:3])   
print(x1[3:])    
print(x1[1:4])   
print(x1[::2])   
print(x1[::-1])  


[3 4 0]
[3 8 6]
[4 0 3]
[3 0 8]
[6 8 3 0 4 3]


In [ ]:
x2 = np.array([[12, 1, 3, 7],
               [4, 0, 2, 3],
               [0, 0, 6, 9]])
print(x2[:2, :3]) 
print(x2[:3, ::2]) 
print(x2[::-1, ::-1])

[[12  1  3]
 [ 4  0  2]]
[[12  3]
 [ 4  2]
 [ 0  6]]
[[ 9  6  0  0]
 [ 3  2  0  4]
 [ 7  3  1 12]]


In [ ]:
print(x2[:, 0]) 
print(x2[0, :]) 
print(x2[0])     


[12  4  0]
[12  1  3  7]
[12  1  3  7]


In [ ]:
x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

[[99  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [ ]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

x = np.array([1, 2, 3])
print(x.reshape((1, 3))) 
print(x.reshape((3, 1)))

# Using np.newaxis
print(x[np.newaxis, :])
print(x[:, np.newaxis])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])


print(np.concatenate([x, y]))
print(np.concatenate([x, y, z]))

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid, grid]))       
print(np.concatenate([grid, grid], axis=1)) 


print(np.vstack([x, grid]))
y = np.array([[99], [99]])
print(np.hstack([grid, y]))


[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [1 2 3]
 [4 5 6]]
[[ 1  2  3 99]
 [ 4  5  6 99]]


In [ ]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

grid = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)


left, right = np.hsplit(grid, [2])
print(left)
print(right)


[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
